### ISSUE TITLE
Improper importation from suggested 'import' statement in README

### ISSUE THREAD

**Issue by j4mesli** [Danetag/ntc-ts#23]
Hello! I believe that your library is deprecated/broken in some way. For reference, I am utilizing your library on an Express.ts application. When I installed and attempted to import the module into my web-app, it game me the *ts(7016)* error. Specifically, it outputted the following text:

```ts
Could not find a declaration file for module 'ntc-ts'. 
'c:/Users/Owner/Desktop/backend/node_modules/ntc-ts/dist/ntc-ts.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/ntc-ts` if it exists or add a new declaration (.d.ts) file containing `declare module 'ntc-ts';`
ts(7016)
```

I attempted to implement an ambient module declaration through the *index.d.ts* file within the *node_modules* directory for 'ntc-ts' which didn't cause any changes. Implementing the following changes in the *index.d.ts* file and *App.ts* file of my web-app that allowed the file to be imported, but attempted to use/implement any method, type, or property within the entirety of the library would cause the file to crash, specifically from the last line in the *ntc-ts.modern.js* file in the *dist* directory.

### index.d.ts
```ts
declare module '*'; // my addition
export * from './colors/minimal';
export * from './colors/original';
export * from './ntc';
```

### App.ts
```ts
// import { getColorName, initColors, ORIGINAL_COLORS } from "ntc-ts";
import * as ntcts from "ntc-ts"; // imports without errors, but doesn't allow for utilization of anything from the library
```

# Quick-'n-dirty fix
I did manage to find a quick-'n-dirty fix to the error at hand by taking all the .ts files from the 'src' folder in the 'ntc-ts' module in the *node_modules* directory and placing them in my root directory where the *App.ts* file is located. Example below:
### My Project Directory (after changes):
```
node_modules
json
public
src ---
      |
      ---App.ts
      ---functions (where I added the contents of the src folder)
                 |
                 ntc-ts (the folder I created to store the contents of the src folder in) ---
                      |
                      colors (from imported src folder) ---
                           |
                           minimal.ts (from imported src folder)
                           original.ts (from imported src folder)
                      index.ts (from imported src folder)
                      ntc.ts (from imported src folder)
                      types.ts (from imported src folder)
```
### index.ts (after relocation)
```ts
export * from './colors/minimal'
export * from './colors/original'
export * from './ntc'
export * from './colors/minimal'
export * from './colors/original'
```
### App.ts (after changes)
```ts
// import { getColorName, initColors, ORIGINAL_COLORS } from "ntc-ts";
// import * as ntcts from "ntc-ts";
import * as ntcts from "./functions/ntc-ts/index"; // local import from relocated src folder
```

Now, everything works as intended and as demonstrated from the README, but you need to prefix everything with `ntcts`
### Example:
```ts
// initColors(ORIGINAL_COLORS);
ntcts.initColors(ntcts.ORIGINAL_COLORS); // this will work instead of the previously stated one due to our method of importation

// const color01 = getColorName("#000");
const color01 = ntcts.getColorName("#000") // as will this
// const color01 = getColorName("#9399A7");
const color01 = ntcts.getColorName("#9399A7") // and this
```

Hopefully this helped specify some new stuff for you to work on if/when you can! Thanks again for creating this!

**Comment by Danetag** [comment]
Hi @j4mesli , thanks for your interest in this lib and taking the time to describe your issue!

Seems like the `*.ts` files were not generated on build in the `/dist` folder, so I created a [PR](https://github.com/Danetag/ntc-ts/pull/24) to address this issue.

Let me know if that fixes it for you!
